Traceback (most recent call last):
  File "/home/lua/Documents/Code/gpt3-bot/main.py", line 18, in <module>
    youtube_dl.utils.bug_reports_message = lambda: ''
NameError: name 'youtube_dl' is not defined